apiVersion: v1
kind: Namespace
metadata:
  name: orders
---
apiVersion: v1
kind: Namespace
metadata:
  name: inventory
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
---
apiVersion: v1
kind: Namespace
metadata:
  name: console
